# [Refactoring Agent] Optimization: Ensure Z-ORDERING on high cardinality columns for performance.
# [Refactoring Agent] Security: All hardcoded credentials have been replaced with dbutils.secrets.get calls (simulated).
# BRONZE LAYER INGESTION
# Generated by Shift-T Architect Agent
# Source: DimCategory.py

from config import Config
from utils import add_ingestion_metadata
from delta.tables import *
from pyspark.sql.functions import *
# [ORIGINAL READ LOGIC (Adapted)]
# We keep the source reading logic active to define 'df_source'
# COMMAND ----------
# Title: DimCategory.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Bronze / Source
# JDBC connection details (use dbutils.secrets for credentials)
db_url = dbutils.secrets.get(scope="jdbc-secrets", key="prod-url")
db_user = dbutils.secrets.get(scope="jdbc-secrets", key="prod-user")
db_password = dbutils.secrets.get(scope="jdbc-secrets", key="prod-password")

# SSIS query: SELECT categoryid,categoryname FROM Production.Categories WHERE categoryid > ?
# For migration, parameterize the value (e.g., categoryid > 0)
categoryid_min = 0  # Replace with widget/parameter if needed
sql_query = f"SELECT categoryid, categoryname FROM Production.Categories WHERE categoryid > {categoryid_min}"

# Read source data explicitly
source_df = (
    spark.read.format("jdbc")
    .option("url", db_url)
    .option("user", db_user)
    .option("password", db_password)
    .option("dbtable", f"({sql_query}) as src")
    .load()
)

# 3. Transformations (Apply Logic)
# No lookups or complex logic; just direct mapping

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
target_table_name = "DimCategory"
bk_cols = ["categoryid"]
sk_col = "CategoryKey"

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except Exception:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = source_df.join(df_target, on=bk_cols, how="left")
else:
    df_joined = source_df.withColumn(sk_col, lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)

# 4. Union
staged_df = df_existing.unionByName(df_new)

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    # Define the unknown row explicitly
    unknown_row = {
        "categoryid": -1,
        "categoryname": "Unknown",
        "CategoryKey": -1
    }
    # Check if unknown exists
    if df.filter(col("CategoryKey") == -1).count() == 0:
        unknown_df = spark.createDataFrame([unknown_row], schema=df.schema)
        df = df.unionByName(unknown_df)
    return df

staged_df = ensure_unknown_member(staged_df)

# 4. Mandatory Type Casting (STRICT)
# Target schema (assumed from context):
#   CategoryKey: INTEGER (Surrogate Key)
#   categoryid: INTEGER (Business Key)
#   categoryname: STRING
staged_df = staged_df.withColumn("CategoryKey", col("CategoryKey").cast("integer"))
staged_df = staged_df.withColumn("categoryid", col("categoryid").cast("integer"))
staged_df = staged_df.withColumn("categoryname", col("categoryname").cast("string"))

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Idempotent overwrite (no SCD logic needed for static dimension)
# [DISABLED_BY_ARCHITECT] staged_df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table_name)

# 6. Optimization (Z-ORDER)
deltaTable = DeltaTable.forName(spark, target_table_name)
deltaTable.optimize().executeZOrderBy("categoryid")


# Apply Bronze Standard
# NOTE: We assume 'df_source' is defined in the original code. 
# If the original code used 'df' or another name, we attempt to alias it.
if 'df_source' not in locals() and 'df' in locals():
    df_source = df

df_bronze = add_ingestion_metadata(df_source)

# Write to Delta
target_table = f"{Config.CATALOG}.{Config.SCHEMA_BRONZE}.DimCategory"
df_bronze.write.format("delta").mode("append").option("mergeSchema", "true").saveAsTable(target_table)
