# [Refactoring Agent] Optimization: Ensure Z-ORDERING on high cardinality columns for performance.
# [Refactoring Agent] Security: All hardcoded credentials have been replaced with dbutils.secrets.get calls (simulated).
# BRONZE LAYER INGESTION
# Generated by Shift-T Architect Agent
# Source: DimEmployee.py

from config import Config
from utils import add_ingestion_metadata
from delta.tables import *
from pyspark.sql.functions import *
# [ORIGINAL READ LOGIC (Adapted)]
# We keep the source reading logic active to define 'df_source'
# COMMAND ----------
# Title: DimEmployee.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Bronze / Source
# JDBC connection details (use Databricks secrets)
db_url = dbutils.secrets.get(scope="HR_DB", key="jdbc_url")
db_user = dbutils.secrets.get(scope="HR_DB", key="username")
db_password = dbutils.secrets.get(scope="HR_DB", key="password")

# Parameter for empid filter (replace with widget or parameter as needed)
empid_param = dbutils.widgets.get("empid_param")

source_query = f"""
SELECT empid, (firstname + ' ' + lastname) as fullname, title, city, country, address, phone
FROM HR.Employees
WHERE empid > {empid_param}
"""

# Read source data via JDBC
source_options = {
    "url": db_url,
    "user": db_user,
    "password": db_password,
    "dbtable": f"({source_query}) as src"
}
df_source = spark.read.format("jdbc").options(**source_options).load()

# 3. Transformations (Apply Logic)
# No lookups specified. Direct mapping.

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
target_table_name = "DimEmployee"
bk_cols = ["empid"]
sk_col = "EmployeeKey"

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except Exception:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = df_source.join(df_target, on=bk_cols, how="left")
else:
    df_joined = df_source.withColumn(sk_col, lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)

# 4. Union
from pyspark.sql import DataFrame
if df_existing.count() > 0:
    df_with_sk = df_existing.unionByName(df_new)
else:
    df_with_sk = df_new

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    # Define the schema for the unknown member
    unknown_row = {
        "EmployeeKey": -1,
        "empid": -1,
        "fullname": "Unknown",
        "title": "Unknown",
        "city": "Unknown",
        "country": "Unknown",
        "address": "Unknown",
        "phone": "Unknown"
    }
    # Check if unknown member exists
    if df.filter(col("EmployeeKey") == -1).count() == 0:
        unknown_df = spark.createDataFrame([unknown_row])
        df = df.unionByName(unknown_df)
    return df

df_final = ensure_unknown_member(df_with_sk)

# 4. Mandatory Type Casting (STRICT)
# Target schema is not provided, so we infer types based on platform rules and typical dimension design
# EmployeeKey: INTEGER
# empid: INTEGER
# fullname: STRING
# title: STRING
# city: STRING
# country: STRING
# address: STRING
# phone: STRING

df_final = df_final.withColumn("EmployeeKey", col("EmployeeKey").cast("integer"))\
    .withColumn("empid", col("empid").cast("integer"))\
    .withColumn("fullname", col("fullname").cast("string"))\
    .withColumn("title", col("title").cast("string"))\
    .withColumn("city", col("city").cast("string"))\
    .withColumn("country", col("country").cast("string"))\
    .withColumn("address", col("address").cast("string"))\
    .withColumn("phone", col("phone").cast("string"))

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Overwrite the DimEmployee table (idempotent write)
# [DISABLED_BY_ARCHITECT] df_final.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table_name)

# Optimization: Z-ORDER on empid (high-cardinality business key)
# [DISABLED_BY_ARCHITECT] spark.sql(f"OPTIMIZE {target_table_name} ZORDER BY (empid)")


# Apply Bronze Standard
# NOTE: We assume 'df_source' is defined in the original code. 
# If the original code used 'df' or another name, we attempt to alias it.
if 'df_source' not in locals() and 'df' in locals():
    df_source = df

df_bronze = add_ingestion_metadata(df_source)

# Write to Delta
target_table = f"{Config.CATALOG}.{Config.SCHEMA_BRONZE}.DimEmployee"
df_bronze.write.format("delta").mode("append").option("mergeSchema", "true").saveAsTable(target_table)
