# [Refactoring Agent] Optimization: Ensure Z-ORDERING on high cardinality columns for performance.
# [Refactoring Agent] Security: All hardcoded credentials have been replaced with dbutils.secrets.get calls (simulated).
# BRONZE LAYER INGESTION
# Generated by Shift-T Architect Agent
# Source: DimSupplier.py

from config import Config
from utils import add_ingestion_metadata
from delta.tables import *
from pyspark.sql.functions import *
# [ORIGINAL READ LOGIC (Adapted)]
# We keep the source reading logic active to define 'df_source'
# COMMAND ----------
# Title: DimSupplier.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Bronze / Source
# JDBC connection details (use dbutils.secrets for credentials)
db_url = dbutils.secrets.get(scope="jdbc-secrets", key="db-url")
db_user = dbutils.secrets.get(scope="jdbc-secrets", key="db-user")
db_password = dbutils.secrets.get(scope="jdbc-secrets", key="db-password")

# Parameter for supplierid threshold (replace with widget or parameter as needed)
supplierid_threshold = 0  # Default, replace with dbutils.widgets.get or parameterization

source_query = f"""
SELECT supplierid, companyname, address, postalcode, phone, city, country
FROM Production.Suppliers
WHERE supplierid > {supplierid_threshold}
"""

df_source = spark.read.format("jdbc") \
    .option("url", db_url) \
    .option("user", db_user) \
    .option("password", db_password) \
    .option("dbtable", f"({source_query}) as src") \
    .load()

# 3. Transformations (Apply Logic)
# No lookups specified. Direct mapping.

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
target_table_name = "dbo.DimSupplier"
bk_cols = ["supplierid"]
sk_col = "SupplierKey"

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except Exception:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = df_source.join(df_target, on=bk_cols, how="left")
else:
    df_joined = df_source.withColumn(sk_col, lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)

# 4. Union
from pyspark.sql import DataFrame

def union_by_name(df1: DataFrame, df2: DataFrame) -> DataFrame:
    # Ensure both DataFrames have the same columns in the same order
    cols = [sk_col] + [c for c in df1.columns if c != sk_col]
    return df1.select(*cols).unionByName(df2.select(*cols))

df_with_sk = union_by_name(df_existing, df_new)

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    # Define the schema for the unknown member
    unknown_row = {
        sk_col: -1,
        "supplierid": -1,
        "companyname": "Unknown",
        "address": "Unknown",
        "postalcode": "Unknown",
        "phone": "Unknown",
        "city": "Unknown",
        "country": "Unknown"
    }
    # Check if unknown member exists
    if df.filter(col(sk_col) == -1).count() == 0:
        unknown_df = spark.createDataFrame([unknown_row])
        df = df.unionByName(unknown_df)
    return df

df_final = ensure_unknown_member(df_with_sk)

# 4. Mandatory Type Casting (STRICT)
# Target schema is not provided, so infer types based on platform rules and SSIS types
# supplierid: DT_I4 -> INTEGER
# companyname: DT_WSTR -> STRING
# address: DT_WSTR -> STRING
# postalcode: DT_WSTR -> STRING
# phone: DT_WSTR -> STRING
# city: DT_WSTR -> STRING
# country: DT_WSTR -> STRING
# SupplierKey: Surrogate Key -> INTEGER

df_final = df_final.withColumn("SupplierKey", col("SupplierKey").cast("integer")) \
    .withColumn("supplierid", col("supplierid").cast("integer")) \
    .withColumn("companyname", col("companyname").cast("string")) \
    .withColumn("address", col("address").cast("string")) \
    .withColumn("postalcode", col("postalcode").cast("string")) \
    .withColumn("phone", col("phone").cast("string")) \
    .withColumn("city", col("city").cast("string")) \
    .withColumn("country", col("country").cast("string"))

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Idempotent overwrite of the dimension table
(
    df_final
# [DISABLED_BY_ARCHITECT]     .write
    .format("delta")
    .mode("overwrite")
    .option("overwriteSchema", "true")
# [DISABLED_BY_ARCHITECT]     .saveAsTable(target_table_name)
)

# 6. Optimization (Z-ORDER on Business Key)
deltaTable = DeltaTable.forName(spark, target_table_name)
deltaTable.optimize().zorderBy("supplierid")


# Apply Bronze Standard
# NOTE: We assume 'df_source' is defined in the original code. 
# If the original code used 'df' or another name, we attempt to alias it.
if 'df_source' not in locals() and 'df' in locals():
    df_source = df

df_bronze = add_ingestion_metadata(df_source)

# Write to Delta
target_table = f"{Config.CATALOG}.{Config.SCHEMA_BRONZE}.DimSupplier"
df_bronze.write.format("delta").mode("append").option("mergeSchema", "true").saveAsTable(target_table)
