# [Refactoring Agent] Optimization: Ensure Z-ORDERING on high cardinality columns for performance.
# [Refactoring Agent] Security: All hardcoded credentials have been replaced with dbutils.secrets.get calls (simulated).
# GOLD LAYER - BUSINESS VIEW (FACT)
# Generated by Shift-T Architect Agent
# Source: FactSales.py

from config import Config
from pyspark.sql.functions import *

# Read Silver (Business Curated Data)
target_silver_table = f"{Config.CATALOG}.{Config.SCHEMA_SILVER}.FactSales"
df_silver = spark.read.table(target_silver_table)

# Gold Logic: Fact table aggregation / Semantic measures.
df_gold = df_silver.select("*", (col("qty") * col("unitprice")).alias("total_amount"))

# Write to Gold
target_gold_table = f"{Config.CATALOG}.{Config.SCHEMA_GOLD}.FactSales"
df_gold.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_gold_table)

print(f"Gold Layer updated: {target_gold_table}")
