# COMMAND ----------
# Title: Conditional_Split_Transformation.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *

# 2. Reading Bronze / Source
# NOTE: No explicit source provided in task. Replace 'source_table' with actual source if known.
df_source = spark.read.table("bronze.Product")

# 3. Transformations (Apply Logic)
# No conditional split logic specified in the task. Passing through all columns with explicit type casting per schema.
df_transformed = df_source.select(
    col("ProductID").cast(IntegerType()).alias("ProductID"),
    col("Name").cast(IntegerType()).alias("Name"),
    col("ProductNumber").cast(StringType()).alias("ProductNumber"),
    col("Color").cast(StringType()).alias("Color"),
    col("SafetyStockLevel").cast(StringType()).alias("SafetyStockLevel"),
    col("ListPrice").cast(DecimalType(19, 4)).alias("ListPrice"),
    col("Size").cast(StringType()).alias("Size")
)

# 4. Lookup Logic (if any)
# No lookups specified in this task.

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Standard overwrite (idempotent) since no SCD or merge logic is required for 'Standard Table'.
df_transformed.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("silver.Product")

# Optional: Z-ORDER optimization on high-cardinality columns (e.g., ProductID)
spark.sql("OPTIMIZE silver.Product ZORDER BY (ProductID)")
