# COMMAND ----------
# Title: EventHandler.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *

# 2. Reading Bronze / Source
# No source inputs specified in task definition. Placeholder for source DataFrame.
df_source = spark.createDataFrame([], StructType([
    StructField("ProductID", IntegerType(), False),
    StructField("Name", IntegerType(), False),
    StructField("ProductNumber", StringType(), False),
    StructField("Color", StringType(), False),
    StructField("SafetyStockLevel", StringType(), False),
    StructField("ListPrice", DecimalType(19, 4), False),
    StructField("Size", StringType(), False)
]))

# 3. Transformations (Apply Logic)
# No transformation logic specified. Schema enforced as per target definition.
df_transformed = df_source.select(
    col("ProductID").cast(IntegerType()).alias("ProductID"),
    col("Name").cast(IntegerType()).alias("Name"),
    col("ProductNumber").cast(StringType()).alias("ProductNumber"),
    col("Color").cast(StringType()).alias("Color"),
    col("SafetyStockLevel").cast(StringType()).alias("SafetyStockLevel"),
    col("ListPrice").cast(DecimalType(19, 4)).alias("ListPrice"),
    col("Size").cast(StringType()).alias("Size")
)

# 4. Lookup Logic (if any)
# No lookups specified.

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Standard overwrite pattern (idempotent) since no SCD or identity logic is required.
target_table = "Product"
df_transformed.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table)

# Optional: Z-ORDER optimization if ProductNumber is high-cardinality
# spark.sql(f"OPTIMIZE {target_table} ZORDER BY (ProductNumber)")
