# COMMAND ----------
# Title: Execute SQL Task.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *

# 2. Reading Bronze / Source
# NOTE: No explicit source defined in task. Placeholder for source DataFrame.
df_source = spark.read.table("bronze.Product")  # Replace with actual source if different

# 3. Transformations (Apply Logic)
# Explicitly cast all columns to match target schema
# (Context Over Assumption: Use Target Schema types)
df_casted = df_source.select(
    col("ProductID").cast(IntegerType()).alias("ProductID"),
    col("Name").cast(IntegerType()).alias("Name"),
    col("ProductNumber").cast(StringType()).alias("ProductNumber"),
    col("Color").cast(StringType()).alias("Color"),
    col("SafetyStockLevel").cast(StringType()).alias("SafetyStockLevel"),
    col("ListPrice").cast(DecimalType(19, 4)).alias("ListPrice"),
    col("Size").cast(StringType()).alias("Size")
)

# 4. Lookup Logic (if any)
# No lookups defined in this task.

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Idempotency: Overwrite entire Product table (no SCD or merge needed for standard table)
df_casted.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("test23.Product")

# Optional: Z-ORDER optimization on ProductNumber (high-cardinality business key)
spark.sql("OPTIMIZE test23.Product ZORDER BY (ProductNumber)")
