# COMMAND ----------
# Title: Extracting Data From Sources.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *

# 2. Reading Bronze / Source
# NOTE: Replace 'bronze.product_source' with the actual source table/view name
# Schema enforced as per Target Schema
product_schema = StructType([
    StructField("ProductID", IntegerType(), False),
    StructField("Name", IntegerType(), False),  # Per target schema, Name is INTEGER
    StructField("ProductNumber", StringType(), False),
    StructField("Color", StringType(), False),
    StructField("SafetyStockLevel", StringType(), False),
    StructField("ListPrice", DecimalType(19, 4), False),
    StructField("Size", StringType(), False)
])
df_source = spark.read.table("bronze.product_source")

# 3. Transformations (Apply Logic)
# Explicitly cast all columns to match target schema (Context Over Assumption)
df_casted = df_source.select(
    col("ProductID").cast(IntegerType()).alias("ProductID"),
    col("Name").cast(IntegerType()).alias("Name"),
    col("ProductNumber").cast(StringType()).alias("ProductNumber"),
    col("Color").cast(StringType()).alias("Color"),
    col("SafetyStockLevel").cast(StringType()).alias("SafetyStockLevel"),
    col("ListPrice").cast(DecimalType(19, 4)).alias("ListPrice"),
    col("Size").cast(StringType()).alias("Size")
)

# 4. Lookup Logic (if any)
# No lookups specified in this task.

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Idempotency: Overwrite entire Product table (no SCD, no PK, standard table)
# NOTE: Replace 'silver.Product' with the actual target table name
(
    df_casted
    .write
    .format("delta")
    .mode("overwrite")
    .option("overwriteSchema", "true")
    .saveAsTable("silver.Product")
)

# Optional: Z-ORDER optimization on ProductNumber (high-cardinality business key)
spark.sql("OPTIMIZE silver.Product ZORDER BY (ProductNumber)")
