# COMMAND ----------
# Title: ForEachLoopCont.dtsx Migration
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *

# 2. Reading Bronze / Source
# NOTE: No explicit source defined in task. Replace 'source_table' with actual source if available.
df_source = spark.createDataFrame([], StructType([
    StructField("ProductID", IntegerType(), False),
    StructField("Name", IntegerType(), False),
    StructField("ProductNumber", StringType(), False),
    StructField("Color", StringType(), False),
    StructField("SafetyStockLevel", StringType(), False),
    StructField("ListPrice", DecimalType(19, 4), False),
    StructField("Size", StringType(), False)
]))

# 3. Transformations (Apply Logic)
# No transformation logic specified in task.
df_transformed = df_source.select(
    col("ProductID").cast(IntegerType()).alias("ProductID"),
    col("Name").cast(IntegerType()).alias("Name"),
    col("ProductNumber").cast(StringType()).alias("ProductNumber"),
    col("Color").cast(StringType()).alias("Color"),
    col("SafetyStockLevel").cast(StringType()).alias("SafetyStockLevel"),
    col("ListPrice").cast(DecimalType(19, 4)).alias("ListPrice"),
    col("Size").cast(StringType()).alias("Size")
)

# 4. Lookup Logic (if any)
# No lookups specified.

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Idempotent overwrite (no SCD or merge needed for standard table)
df_transformed.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("Product")

# Optional: Z-ORDER optimization on ProductNumber (high-cardinality business key)
spark.sql("OPTIMIZE Product ZORDER BY (ProductNumber)")
