# COMMAND ----------
# Title: Merge_Join.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *

# 2. Reading Bronze / Source
# NOTE: No explicit source tables defined in task. Replace with actual source table(s) as needed.
df_source = spark.read.table("bronze.Product_source")

# 3. Transformations (Apply Logic)
# Explicitly cast all columns to match target schema
# (Context Over Assumption: Use Target Schema types)
df_transformed = df_source.select(
    col("ProductID").cast(IntegerType()).alias("ProductID"),
    col("Name").cast(IntegerType()).alias("Name"),
    col("ProductNumber").cast(StringType()).alias("ProductNumber"),
    col("Color").cast(StringType()).alias("Color"),
    col("SafetyStockLevel").cast(StringType()).alias("SafetyStockLevel"),
    col("ListPrice").cast(DecimalType(19, 4)).alias("ListPrice"),
    col("Size").cast(StringType()).alias("Size")
)

# 4. Lookup Logic (if any)
# No lookups defined in this task.

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Idempotency: Overwrite the Product table (no SCD or merge pattern required for standard table)
df_transformed.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("gold.Product")

# Optimization: Z-ORDER on high-cardinality columns (e.g., ProductID, ProductNumber)
spark.sql("OPTIMIZE gold.Product ZORDER BY (ProductID, ProductNumber)")
