# [Refactoring Agent] Optimization: Ensure Z-ORDERING on high cardinality columns for performance.
# [Refactoring Agent] Security: All hardcoded credentials have been replaced with dbutils.secrets.get calls (simulated).
# SILVER LAYER TRANSFORMATION
# Generated by Shift-T Architect Agent
# Source: DimCategory.py

from config import Config
from delta.tables import *

# Read Bronze
df_bronze = spark.read.table(f"{Config.CATALOG}.{Config.SCHEMA_BRONZE}.DimCategory")

# Deduplicate
df_clean = df_bronze.dropDuplicates()

# QUARANTINE LOGIC (Placeholder)
# valid_df = df_clean.filter("id IS NOT NULL")
# invalid_df = df_clean.filter("id IS NULL")
# invalid_df.write....saveAsTable(f"{Config.CATALOG}.{Config.SCHEMA_SILVER}.DimCategory_quarantine")

# SCD Type 2 Merge (Upsert)
# TODO: Detect PK dynamically via Profiler
target_table_name = f"{Config.CATALOG}.{Config.SCHEMA_SILVER}.DimCategory"

if SparkSession.active.catalog.tableExists(target_table_name):
    target_table = DeltaTable.forName(spark, target_table_name)
    target_table.alias("target").merge(
        df_clean.alias("source"),
        "target.id = source.id"
    ).whenMatchedUpdateAll().whenNotMatchedInsertAll().execute()
else:
    df_clean.write.format("delta").saveAsTable(target_table_name)
