# [Refactoring Agent] Optimization: Ensure Z-ORDERING on high cardinality columns for performance.
# [Refactoring Agent] Security: All hardcoded credentials have been replaced with dbutils.secrets.get calls (simulated).
# GOLD LAYER - BUSINESS VIEW
# Generated by Shift-T Architect Agent
# Source: DimProduct.py

from config import Config

# Read Silver (Business Curated Data)
target_silver_table = f"{Config.CATALOG}.{Config.SCHEMA_SILVER}.DimProduct"
df_silver = spark.read.table(target_silver_table)

# Gold Logic: Final Business Logic / Aggregations / Aggregated Views
# In this stage, we project the final curated data to the business schema.
# Example: Rename technical columns to business aliases or apply final filters.
df_gold = df_silver.select("*") 

# Write to Gold
target_gold_table = f"{Config.CATALOG}.{Config.SCHEMA_GOLD}.DimProduct"
df_gold.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_gold_table)

print(f"Gold Layer updated: {target_gold_table}")
