# COMMAND ----------
# Title: DimCustomers.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window
import pyspark.sql.functions as F

# 2. Reading Bronze / Source
# -- JDBC connection details (parameterized, no hardcoded secrets)
db_url = dbutils.secrets.get(scope="jdbc-secrets", key="sales_db_url")
db_user = dbutils.secrets.get(scope="jdbc-secrets", key="sales_db_user")
db_password = dbutils.secrets.get(scope="jdbc-secrets", key="sales_db_password")

# -- Parameter for the WHERE clause (custid > ?)
min_custid = dbutils.widgets.get("min_custid") if dbutils.widgets.get("min_custid", None) else "0"

source_query = f"""
    SELECT custid, contactname, city, country, address, phone, postalcode
    FROM Sales.Customers
    WHERE custid > {min_custid}
"""

# -- Read source data explicitly
source_df = (
    spark.read.format("jdbc")
    .option("url", db_url)
    .option("user", db_user)
    .option("password", db_password)
    .option("dbtable", f"({source_query}) as src")
    .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver")
    .load()
)

# 3. Transformations (Apply Logic)
# -- No lookups or additional logic specified

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
target_table_name = "DimCustomer"
bk_cols = ["custid"]
sk_col = "CustomerKey"

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(F.max(F.col(sk_col))).collect()[0][0] or 0
except Exception:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = source_df.join(df_target, on=bk_cols, how="left")
else:
    df_joined = source_df.withColumn(sk_col, F.lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(F.col(sk_col).isNotNull())
df_new = df_joined.filter(F.col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, F.row_number().over(window_spec) + max_sk)

df_with_sk = df_existing.unionByName(df_new)

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    # Define the schema for the unknown member
    unknown_row = {
        "CustomerKey": -1,
        "custid": -1,
        "contactname": "Unknown",
        "city": "Unknown",
        "country": "Unknown",
        "address": "Unknown",
        "phone": "Unknown",
        "postalcode": "Unknown"
    }
    # Check if unknown member exists
    if df.filter(col("CustomerKey") == -1).count() == 0:
        unknown_df = spark.createDataFrame([unknown_row], schema=df.schema)
        df = df.unionByName(unknown_df)
    return df

df_with_sk = ensure_unknown_member(df_with_sk)

# 4. Mandatory Type Casting (STRICT)
# -- Target schema is not provided, so we infer types based on platform rules and common conventions
# -- If you have a schema registry, replace the following with explicit types
casted_df = (
    df_with_sk
    .withColumn("CustomerKey", col("CustomerKey").cast("integer"))
    .withColumn("custid", col("custid").cast("integer"))
    .withColumn("contactname", col("contactname").cast("string"))
    .withColumn("city", col("city").cast("string"))
    .withColumn("country", col("country").cast("string"))
    .withColumn("address", col("address").cast("string"))
    .withColumn("phone", col("phone").cast("string"))
    .withColumn("postalcode", col("postalcode").cast("string"))
)

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# -- Overwrite the dimension table (idempotent load)
(
    casted_df
    .orderBy("CustomerKey")
    .write
    .format("delta")
    .mode("overwrite")
    .option("overwriteSchema", "true")
    .saveAsTable(target_table_name)
)

# 6. Optimization (Z-ORDER on Business Key)
spark.sql(f"OPTIMIZE {target_table_name} ZORDER BY (custid)")
