# COMMAND ----------
# Title: DimCustomers.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window
import pyspark.sql.functions as F

# 2. Reading Bronze / Source
# -- JDBC connection details (replace with your actual secret scope/keys)
db_url = dbutils.secrets.get(scope="jdbc-secrets", key="sales-db-url")
db_user = dbutils.secrets.get(scope="jdbc-secrets", key="sales-db-user")
db_password = dbutils.secrets.get(scope="jdbc-secrets", key="sales-db-password")

# -- Parameter for the WHERE clause (custid > ?)
custid_min = dbutils.widgets.get("custid_min") if dbutils.widgets.get("custid_min", None) else "0"

sql_query = f"""
SELECT custid, contactname, city, country, address, phone, postalcode
FROM Sales.Customers
WHERE custid > {custid_min}
"""

df_source = (
    spark.read.format("jdbc")
    .option("url", db_url)
    .option("user", db_user)
    .option("password", db_password)
    .option("dbtable", f"({sql_query}) as src")
    .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver")
    .load()
)

# 3. Transformations (Apply Logic)
# -- Map source columns to target columns (assuming 1:1 mapping)
# -- If target schema is not provided, we infer reasonable types and names
# -- Target Table: DimCustomer
# -- Columns: CustomerKey (SK), CustomerAlternateKey (BK), ContactName, City, Country, Address, Phone, PostalCode

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
target_table_name = "DimCustomer"
bk_cols = ["custid"]
sk_col = "CustomerKey"

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(F.max(F.col(sk_col))).collect()[0][0] or 0
except:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = df_source.join(df_target, on=bk_cols, how="left")
else:
    df_joined = df_source.withColumn(sk_col, F.lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(F.col(sk_col).isNotNull())
df_new = df_joined.filter(F.col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, F.row_number().over(window_spec) + max_sk)

# 4. Union
from functools import reduce
df_with_sk = df_existing.unionByName(df_new)

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    # Define the schema for the unknown member
    unknown_row = {
        "CustomerKey": -1,
        "custid": -1,
        "contactname": "Unknown",
        "city": "Unknown",
        "country": "Unknown",
        "address": "Unknown",
        "phone": "Unknown",
        "postalcode": "Unknown"
    }
    # Check if unknown exists
    if df.filter(col("CustomerKey") == -1).count() == 0:
        df_unknown = spark.createDataFrame([unknown_row], schema=df.schema)
        df = df.unionByName(df_unknown)
    return df

df_with_sk = ensure_unknown_member(df_with_sk)

# 4. Mandatory Type Casting (STRICT)
# -- Define target schema explicitly (as not provided)
target_schema = [
    StructField("CustomerKey", IntegerType(), False),
    StructField("custid", IntegerType(), False),
    StructField("contactname", StringType(), True),
    StructField("city", StringType(), True),
    StructField("country", StringType(), True),
    StructField("address", StringType(), True),
    StructField("phone", StringType(), True),
    StructField("postalcode", StringType(), True)
]

for field in target_schema:
    col_name = field.name
    target_type = field.dataType.simpleString()
    if col_name in df_with_sk.columns:
        df_with_sk = df_with_sk.withColumn(col_name, col(col_name).cast(target_type))

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# -- Overwrite the table (idempotent load)
df_with_sk.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table_name)

# 6. Optimization (Z-ORDER on Business Key)
spark.sql(f"OPTIMIZE {target_table_name} ZORDER BY (custid)")
