# COMMAND ----------
# Title: FactSales.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window
import pyspark.sql.functions as F

# 2. Reading Bronze / Source
# NOTE: No target schema provided. Skipping type enforcement and surrogate key logic.

# --- Input 1: Orders + OrderDetails + Products ---
db_url = dbutils.secrets.get(scope="jdbc", key="dw_url")
db_user = dbutils.secrets.get(scope="jdbc", key="dw_user")
db_password = dbutils.secrets.get(scope="jdbc", key="dw_password")

sql_query_1 = '''select O.orderid,O.custid,O.empid,O.shipperid,P.categoryid,P.supplierid,OD.qty,OD.unitprice,OD.discount,OD.productid from Sales.orders O 
 INNER JOIN Sales.OrderDetails OD
 ON O.orderid =OD.orderid
 inner join Production.Products P
 ON P.productid=OD.productid'''

df_orders = spark.read.format("jdbc") \
    .option("url", db_url) \
    .option("user", db_user) \
    .option("password", db_password) \
    .option("dbtable", f"({sql_query_1}) as src") \
    .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver") \
    .load()

# --- Input 2: tempStage joined with V_DimProduct ---
sql_query_2 = '''SELECT T.* 
FROM tempStage T 
INNER JOIN dw..V_DimProduct P 
ON P.productid = T.productid'''

df_tempstage = spark.read.format("jdbc") \
    .option("url", db_url) \
    .option("user", db_user) \
    .option("password", db_password) \
    .option("dbtable", f"({sql_query_2}) as src") \
    .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver") \
    .load()

# 3. Transformations (Apply Logic)
# No transformation logic specified in task definition.

# 4. Writing to Silver/Gold (Apply Platform Pattern)
# Output: [FactSales], [tempStage]
# Since no SCD or surrogate key logic is specified and no schema is provided, we will overwrite the tables.

# Write FactSales
# (Assume catalog and schema are set in Spark session)
df_orders.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("FactSales")

# Write tempStage
# (Assume catalog and schema are set in Spark session)
df_tempstage.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("tempStage")
