# COMMAND ----------
# Title: DimCategory.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Bronze / Source
# JDBC connection details (use dbutils.secrets for credentials)
db_url = dbutils.secrets.get(scope="jdbc-secrets", key="db_url")
db_user = dbutils.secrets.get(scope="jdbc-secrets", key="db_user")
db_password = dbutils.secrets.get(scope="jdbc-secrets", key="db_password")

# Parameter for categoryid filter (replace with widget or parameter as needed)
categoryid_param = dbutils.widgets.get("categoryid_param")

sql_query = f"""
SELECT categoryid, categoryname FROM Production.Categories
WHERE categoryid > {categoryid_param}
"""

# Read source data explicitly via JDBC
source_df = (
    spark.read.format("jdbc")
    .option("url", db_url)
    .option("user", db_user)
    .option("password", db_password)
    .option("dbtable", f"({sql_query}) as src")
    .load()
)

# 3. Transformations (Apply Logic)
# No lookups or complex logic required for this dimension

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
target_table_name = "DimCategory"
bk_cols = ["categoryid"]
sk_col = "CategorySK"

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except Exception:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = source_df.join(df_target, on=bk_cols, how="left")
else:
    df_joined = source_df.withColumn(sk_col, lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)

# 4. Union
category_df = df_existing.unionByName(df_new)

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    # Define the schema for the unknown member
    unknown_row = {
        "categoryid": -1,
        "categoryname": "Unknown",
        "CategorySK": -1
    }
    # Check if unknown member exists
    if df.filter(col("categoryid") == -1).count() == 0:
        unknown_df = spark.createDataFrame([unknown_row], schema=df.schema)
        df = df.unionByName(unknown_df)
    return df

category_df = ensure_unknown_member(category_df)

# 4. Mandatory Type Casting (STRICT)
# Target schema is not provided, so we infer from business logic and platform rules
# categoryid: INTEGER, categoryname: STRING, CategorySK: INTEGER
category_df = (
    category_df
    .withColumn("categoryid", col("categoryid").cast("integer"))
    .withColumn("categoryname", col("categoryname").cast("string"))
    .withColumn("CategorySK", col("CategorySK").cast("integer"))
)

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Overwrite/merge logic for dimension table
# Use Delta Lake MERGE for idempotency

delta_table = DeltaTable.forName(spark, target_table_name)

# Prepare staged data for merge
staged_df = category_df

# Merge logic: match on business key (categoryid)
delta_table.alias("target").merge(
    staged_df.alias("source"),
    "target.categoryid = source.categoryid"
).whenMatchedUpdateAll(
).whenNotMatchedInsertAll(
).execute()
