# COMMAND ----------
# Title: DimShipper.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Bronze / Source
# Extract JDBC connection details securely
jdbc_url = dbutils.secrets.get(scope="jdbc-secrets", key="sales-db-url")
jdbc_user = dbutils.secrets.get(scope="jdbc-secrets", key="sales-db-user")
jdbc_password = dbutils.secrets.get(scope="jdbc-secrets", key="sales-db-password")

# Parameter for shipperid threshold (replace with widget or parameter as needed)
shipperid_threshold = dbutils.widgets.get("shipperid_threshold")

# Build parameterized query
source_query = f"SELECT * FROM Sales.Shippers WHERE shipperid > {shipperid_threshold}"

# Read source data explicitly via JDBC
source_df = (
    spark.read.format("jdbc")
    .option("url", jdbc_url)
    .option("user", jdbc_user)
    .option("password", jdbc_password)
    .option("dbtable", f"({source_query}) as src")
    .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver")
    .load()
)

# 3. Transformations (Apply Logic)
# No lookups or complex logic specified. Direct mapping.
df_staged = source_df

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
target_table_name = "DimShipper"
bk_cols = ["shipperid"]  # Business Key
sk_col = "DimShipperID"  # Surrogate Key (assumed name)

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except Exception:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = df_staged.join(df_target, on=bk_cols, how="left")
else:
    df_joined = df_staged.withColumn(sk_col, lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)

# 4. Union
final_df = df_existing.unionByName(df_new)

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    # Define the schema for the unknown member
    unknown_row = {
        "shipperid": -1,
        "companyname": "Unknown",
        "phone": "Unknown",
        sk_col: -1
    }
    # Check if unknown member exists
    if df.filter(col("shipperid") == -1).count() == 0:
        unknown_df = spark.createDataFrame([unknown_row], schema=df.schema)
        df = df.unionByName(unknown_df)
    return df

final_df = ensure_unknown_member(final_df)

# 4. Mandatory Type Casting (STRICT)
# Define target schema explicitly (example, adjust as per actual schema)
target_schema = [
    {"name": "DimShipperID", "type": "INTEGER"},
    {"name": "shipperid", "type": "INTEGER"},
    {"name": "companyname", "type": "STRING"},
    {"name": "phone", "type": "STRING"}
]
for field in target_schema:
    col_name = field["name"]
    target_type = field["type"]
    if col_name in final_df.columns:
        final_df = final_df.withColumn(col_name, col(col_name).cast(target_type))

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Overwrite/merge logic for idempotency
# Delta Lake MERGE pattern (SCD Type 1 for dimension, as no history columns specified)
delta_table = DeltaTable.forName(spark, target_table_name)
delta_table.alias("target").merge(
    final_df.alias("source"),
    "target.shipperid = source.shipperid"
).whenMatchedUpdateAll().whenNotMatchedInsertAll().execute()

# Optimization: Z-ORDER on business key
spark.sql(f"OPTIMIZE {target_table_name} ZORDER BY (shipperid)")
