# COMMAND ----------
# Title: DimSupplier.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Bronze / Source
# JDBC connection details (use Databricks secrets)
db_url = dbutils.secrets.get('jdbc', 'sqlserver_url')
db_user = dbutils.secrets.get('jdbc', 'sqlserver_user')
db_password = dbutils.secrets.get('jdbc', 'sqlserver_password')

# Parameter for supplierid threshold (replace with widget or parameter as needed)
supplierid_threshold = dbutils.widgets.get('supplierid_threshold') if 'supplierid_threshold' in dbutils.widgets.get('') else 0

source_query = f"""
SELECT supplierid, companyname, address, postalcode, phone, city, country
FROM Production.Suppliers
WHERE supplierid > {supplierid_threshold}
"""

df_source = spark.read.format("jdbc") \
    .option("url", db_url) \
    .option("user", db_user) \
    .option("password", db_password) \
    .option("dbtable", f"({source_query}) as src") \
    .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver") \
    .load()

# 3. Transformations (Apply Logic)
# No lookups or complex transforms per task definition

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
target_table_name = "dbo.DimSupplier"
bk_cols = ["supplierid"]
sk_col = "SupplierKey"

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except Exception:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = df_source.join(df_target, on=bk_cols, how="left")
else:
    df_joined = df_source.withColumn(sk_col, lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)

# 4. Union
from pyspark.sql import DataFrame

def union_by_name_safe(df1: DataFrame, df2: DataFrame) -> DataFrame:
    # Ensure both DataFrames have the same columns in the same order
    cols = sorted(set(df1.columns) | set(df2.columns))
    df1 = df1.select([col(c) if c in df1.columns else lit(None).alias(c) for c in cols])
    df2 = df2.select([col(c) if c in df2.columns else lit(None).alias(c) for c in cols])
    return df1.unionByName(df2)

df_with_sk = union_by_name_safe(df_existing, df_new)

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    # Define the schema for the unknown member
    unknown_row = {
        "SupplierKey": -1,
        "supplierid": -1,
        "companyname": "Unknown",
        "address": "Unknown",
        "postalcode": "Unknown",
        "phone": "Unknown",
        "city": "Unknown",
        "country": "Unknown"
    }
    # Check if unknown member exists
    if df.filter(col("SupplierKey") == -1).count() == 0:
        unknown_df = spark.createDataFrame([unknown_row])
        df = union_by_name_safe(df, unknown_df)
    return df

df_final = ensure_unknown_member(df_with_sk)

# 4. Mandatory Type Casting (STRICT)
# Target schema (from context):
# SupplierKey: INTEGER
# supplierid: INTEGER
# companyname: STRING
# address: STRING
# postalcode: STRING
# phone: STRING
# city: STRING
# country: STRING

cast_map = {
    "SupplierKey": "integer",
    "supplierid": "integer",
    "companyname": "string",
    "address": "string",
    "postalcode": "string",
    "phone": "string",
    "city": "string",
    "country": "string"
}
for col_name, target_type in cast_map.items():
    if col_name in df_final.columns:
        df_final = df_final.withColumn(col_name, col(col_name).cast(target_type))

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Idempotent overwrite (since this is a dimension, not SCD2)
df_final.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table_name)

# Optimization: Z-ORDER on supplierid (high-cardinality business key)
spark.sql(f"OPTIMIZE {target_table_name} ZORDER BY (supplierid)")
