# COMMAND ----------
# Title: FactSales.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Bronze / Source
# Input 1: QUERY: SELECT T.* FROM tempStage T INNER JOIN dw..V_DimProduct P ON P.productid = T.productid;
# Input 2: QUERY: select O.orderid,O.custid,O.empid,O.shipperid,P.categoryid,P.supplierid,OD.qty,OD.unitprice,OD.discount,OD.productid from Sales.orders O 
# INNER JOIN Sales.OrderDetails OD ON O.orderid =OD.orderid
# inner join Production.Products P ON P.productid=OD.productid

# Setup JDBC connection parameters (use dbutils.secrets for credentials)
db_url = dbutils.secrets.get(scope="jdbc-secrets", key="dw-url")
db_user = dbutils.secrets.get(scope="jdbc-secrets", key="dw-user")
db_password = dbutils.secrets.get(scope="jdbc-secrets", key="dw-password")

# Read Input 1
df_input1 = spark.read.format("jdbc") \
    .option("url", db_url) \
    .option("dbtable", "(SELECT T.* FROM tempStage T INNER JOIN dw..V_DimProduct P ON P.productid = T.productid) as src") \
    .option("user", db_user) \
    .option("password", db_password) \
    .load()

# Read Input 2
df_input2 = spark.read.format("jdbc") \
    .option("url", db_url) \
    .option("dbtable", "(select O.orderid,O.custid,O.empid,O.shipperid,P.categoryid,P.supplierid,OD.qty,OD.unitprice,OD.discount,OD.productid from Sales.orders O INNER JOIN Sales.OrderDetails OD ON O.orderid =OD.orderid inner join Production.Products P ON P.productid=OD.productid) as src") \
    .option("user", db_user) \
    .option("password", db_password) \
    .load()

# 3. Transformations (Apply Logic)
# Since no lookups are specified, and the target schema is not provided, we will proceed to stage the data for FactSales.
# If tempStage is a staging table, we write df_input2 to tempStage, then use df_input1 for FactSales.

# 3.1 Write to tempStage (idempotent overwrite)
df_tempStage = df_input2
# Overwrite tempStage table
# Note: Replace 'catalog.schema.tempStage' with the actual catalog/schema if available

df_tempStage.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("tempStage")

# 3.2 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
# Since FactSales is a fact table, we must generate a Surrogate Key (e.g., SalesKey)
# Assume business keys: orderid, productid
# Surrogate Key: SalesKey (INTEGER)
target_table_name = "FactSales"
bk_cols = ["orderid", "productid"]
sk_col = "SalesKey"

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target:
    df_joined = df_input1.join(df_target, on=bk_cols, how="left")
else:
    df_joined = df_input1.withColumn(sk_col, lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)

# 4. Union
# Ensure columns match
df_with_sk = df_existing.unionByName(df_new)

# 4. Mandatory Type Casting (STRICT)
# Since target schema is not provided, we cannot cast columns. In production, you must cast every column to its target type as per schema.
# Example:
# for field in target_schema:
#     col_name = field["name"]
#     target_type = field["type"]
#     if col_name in df_with_sk.columns:
#         df_with_sk = df_with_sk.withColumn(col_name, col(col_name).cast(target_type))

# 5. Writing to FactSales (idempotent overwrite)
df_with_sk.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table_name)
