# [Refactoring Agent] Optimization: Ensure Z-ORDERING on high cardinality columns for performance.
# [Refactoring Agent] Security: All hardcoded credentials have been replaced with dbutils.secrets.get calls (simulated).
# BRONZE LAYER INGESTION
# Generated by Shift-T Architect Agent
# Source: DimSupplier.py

from config import Config
from utils import add_ingestion_metadata
from delta.tables import *
from pyspark.sql.functions import *
# [ORIGINAL READ LOGIC (Adapted)]
# We keep the source reading logic active to define 'df_source'
# COMMAND ----------
# Title: DimSupplier.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Bronze / Source
# -- JDBC connection setup (parameters should be set via widgets or secrets)
db_url = dbutils.secrets.get(scope="jdbc-secrets", key="sqlserver-url")
db_user = dbutils.secrets.get(scope="jdbc-secrets", key="sqlserver-user")
db_password = dbutils.secrets.get(scope="jdbc-secrets", key="sqlserver-password")

# The parameter for supplierid > ? should be provided as a widget or parameter
supplierid_min = int(dbutils.widgets.get("supplierid_min"))
source_query = f"""
    SELECT supplierid, companyname, address, postalcode, phone, city, country
    FROM Production.Suppliers
    WHERE supplierid > {supplierid_min}
"""

df_source = spark.read.format("jdbc") \
    .option("url", db_url) \
    .option("user", db_user) \
    .option("password", db_password) \
    .option("dbtable", f"({source_query}) as src") \
    .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver") \
    .load()

# 3. Transformations (Apply Logic)
# -- No lookups or additional transformations specified

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
import pyspark.sql.functions as F

target_table_name = "dbo.DimSupplier"
bk_cols = ["supplierid"]
sk_col = "SupplierKey"

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(F.max(F.col(sk_col))).collect()[0][0] or 0
except:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = df_source.join(df_target, on=bk_cols, how="left")
else:
    df_joined = df_source.withColumn(sk_col, F.lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(F.col(sk_col).isNotNull())
df_new = df_joined.filter(F.col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, F.row_number().over(window_spec) + max_sk)

# 4. Union
from functools import reduce
df_with_sk = df_existing.unionByName(df_new)

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    # Define the schema for the unknown member
    unknown_row = {
        "SupplierKey": -1,
        "supplierid": -1,
        "companyname": "Unknown",
        "address": "Unknown",
        "postalcode": "Unknown",
        "phone": "Unknown",
        "city": "Unknown",
        "country": "Unknown"
    }
    # Check if -1 exists
    if df.filter(col("SupplierKey") == -1).count() == 0:
        df_unknown = spark.createDataFrame([unknown_row], schema=df.schema)
        df = df.unionByName(df_unknown)
    return df

df_with_sk = ensure_unknown_member(df_with_sk)

# 4. Mandatory Type Casting (STRICT)
# -- Target schema (STRICT):
# SupplierKey: INTEGER (Surrogate Key)
# supplierid: INTEGER
# companyname: STRING
# address: STRING
# postalcode: STRING
# phone: STRING
# city: STRING
# country: STRING

target_schema = [
    ("SupplierKey", "integer"),
    ("supplierid", "integer"),
    ("companyname", "string"),
    ("address", "string"),
    ("postalcode", "string"),
    ("phone", "string"),
    ("city", "string"),
    ("country", "string")
]

df_final = df_with_sk
for col_name, target_type in target_schema:
    if col_name in df_final.columns:
        df_final = df_final.withColumn(col_name, col(col_name).cast(target_type))

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# -- Overwrite the target table (idempotent load for dimension)
(
    df_final
    .select([name for name, _ in target_schema])
# [DISABLED_BY_ARCHITECT]     .write
    .format("delta")
    .mode("overwrite")
    .option("overwriteSchema", "true")
# [DISABLED_BY_ARCHITECT]     .saveAsTable(target_table_name)
)

# Optional: Z-ORDER optimization on SupplierKey (high-cardinality BK)
# [DISABLED_BY_ARCHITECT] spark.sql(f"OPTIMIZE {target_table_name} ZORDER BY (supplierid)")


# Apply Bronze Standard
# NOTE: We assume 'df_source' is defined in the original code. 
# If the original code used 'df' or another name, we attempt to alias it.
if 'df_source' not in locals() and 'df' in locals():
    df_source = df

df_bronze = add_ingestion_metadata(df_source)

# Write to Delta
target_table = f"{Config.CATALOG}.{Config.SCHEMA_BRONZE}.DimSupplier"
df_bronze.write.format("delta").mode("append").option("mergeSchema", "true").saveAsTable(target_table)
