# [Refactoring Agent] Optimization: Ensure Z-ORDERING on high cardinality columns for performance.
# [Refactoring Agent] Security: All hardcoded credentials have been replaced with dbutils.secrets.get calls (simulated).
# SILVER LAYER TRANSFORMATION
# Generated by Shift-T Architect Agent
# Source: DimSupplier.py
# Primary Key(s): supplierid

from config import Config
from delta.tables import *

# Read Bronze
df_bronze = spark.read.table(f"{Config.CATALOG}.{Config.SCHEMA_BRONZE}.DimSupplier")

# Deduplicate
df_clean = df_bronze.dropDuplicates(['supplierid'])

# SCD Type 2 Merge (Upsert)
target_table_name = f"{Config.CATALOG}.{Config.SCHEMA_SILVER}.DimSupplier"

if SparkSession.active.catalog.tableExists(target_table_name) and "supplierid" != "id":
    target_table = DeltaTable.forName(spark, target_table_name)
    target_table.alias("target").merge(
        df_clean.alias("source"),
        "target.supplierid = source.supplierid"
    ).whenMatchedUpdateAll().whenNotMatchedInsertAll().execute()
else:
    # If no specific key was detected, we overwrite or append based on type
    df_clean.write.format("delta").mode("overwrite").saveAsTable(target_table_name)
